#ifndef MOVEIT_PLANNERS_SBPL_CONFIG_H
#define MOVEIT_PLANNERS_SBPL_CONFIG_H

#define COLLISION_DETECTION_SBPL_ROS_INDIGO     0
#define COLLISION_DETECTION_SBPL_ROS_KINETIC    1

#ifndef COLLISION_DETECTION_SBPL_ROS_VERSION
#error "COLLISION_DETECTION_SBPL_ROS_VERSION must be defined"
#endif

#endif
